import enum
from typing import Optional, Protocol, runtime_checkable, List

class Body:
    text: str
    bytes: bytes

    def clear(self) -> None: ...
    def __len__(self) -> int: ...
    def __str__(self) -> str: ...

class Headers:
    def get(self, key: str) -> Optional[str]: ...
    def set(self, key: str, value: str) -> None: ...
    def append(self, key: str, value: str) -> None: ...
    def delete(self, key: str) -> None: ...
    def has(self, key: str) -> bool: ...
    def clear(self) -> None: ...
    def __len__(self) -> int: ...
    def __str__(self) -> str: ...
    def __getitem__(self, key: str) -> None: ...
    def __setitem__(self, key: str, value: str | None) -> None: ...
    def __delitem__(self, key: str) -> None: ...

class Request:
    method: Method
    url: Url
    version: str
    headers: Headers
    trailers: Headers
    body: Body
    def __str__(self) -> str: ...

class Method(enum.Enum):
    GET = 1
    POST = 2
    PUT = 3
    DELETE = 4

class Url:
    protocol: Optional[str]
    authority: Optional[str]
    username: Optional[str]
    password: Optional[str]
    hostname: Optional[str]
    host: str
    port: Optional[int]
    path: Optional[str]
    search_params: UrlSearchParams
    def __str__(self) -> str: ...

class UrlSearchParams:
    def __getitem__(self, key: str) -> Optional[str]: ...
    def __str__(self) -> str: ...
    def set(self, key: str, value: str) -> None: ...
    def append(self, key: str, value: str) -> None: ...
    def clear(self) -> None: ...
    def delete(self, key: str) -> None: ...

class Response:
    status: int
    version: str
    headers: Headers
    trailers: Headers
    body: Body
    def __str__(self) -> str: ...

class Flow:
    request: Request
    response: Response
    def __str__(self) -> str: ...

@runtime_checkable
class Extension(Protocol):
    def start(self) -> None: ...
    def stop(self) -> None: ...
    def request(self, flow: Flow) -> None: ...
    def response(self, flow: Flow) -> None: ...

def notify(level: int, msg: str) -> None: ...

# Roxy discovers this global list at load
Extensions: List[Extension]
