import enum
from typing import Optional, Protocol as ProtocolType, runtime_checkable, List

class Body:
    text: str
    bytes: bytes

    def clear(self) -> None: ...
    def __len__(self) -> int: ...
    def __str__(self) -> str: ...
    def __repr__(self) -> str: ...

class Headers:
    def get(self, key: str) -> Optional[str]: ...
    def set(self, key: str, value: str) -> None: ...
    def append(self, key: str, value: str) -> None: ...
    def delete(self, key: str) -> None: ...
    def has(self, key: str) -> bool: ...
    def clear(self) -> None: ...
    def __len__(self) -> int: ...
    def __str__(self) -> str: ...
    def __repr__(self) -> str: ...
    def __getitem__(self, key: str) -> None: ...
    def __setitem__(self, key: str, value: str | None) -> None: ...
    def __delitem__(self, key: str) -> None: ...

class Request:
    method: Method
    url: Url
    version: str
    headers: Headers
    trailers: Headers
    body: Body
    def __str__(self) -> str: ...
    def __repr__(self) -> str: ...

class Version(enum.Enum):
    HTTP0_9 = ("HTTP/0.9",)
    HTTP1_0 = ("HTTP/1.0",)
    HTTP1_1 = ("HTTP/1.1",)
    HTTP2_0 = ("HTTP/2.0",)
    HTTP3_0 = ("HTTP/3.0",)

class Method(enum.Enum):
    CONNECT = ("CONNECT",)
    DELETE = ("DELETE",)
    GET = ("GET",)
    HEAD = ("HEAD",)
    OPTIONS = ("OPTIONS",)
    PATCH = ("PATCH",)
    POST = ("POST",)
    PUT = ("PUT",)
    TRACE = ("TRACE",)

class Protocol(enum.Enum):
    HTTP = ("http",)
    HTTPS = ("https",)

class Url:
    protocol: Optional[str]
    authority: Optional[str]
    username: Optional[str]
    password: Optional[str]
    hostname: Optional[str]
    host: str
    port: Optional[int]
    path: Optional[str]
    search_params: UrlSearchParams
    def __str__(self) -> str: ...
    def __repr__(self) -> str: ...

class UrlSearchParams:
    def append(self, key: str, value: str) -> None: ...
    def clear(self) -> None: ...
    def delete(self, key: str) -> None: ...
    def __repr__(self) -> str: ...
    def __getitem__(self, key: str) -> Optional[str]: ...
    def __setitem__(self, key: str, value: str) -> None: ...
    def __str__(self) -> str: ...
    def __len__(self) -> int: ...

class Response:
    status: int
    version: str
    headers: Headers
    trailers: Headers
    body: Body
    def __str__(self) -> str: ...
    def __repr__(self) -> str: ...

class Flow:
    request: Request
    response: Response
    def __str__(self) -> str: ...
    def __repr__(self) -> str: ...

@runtime_checkable
class Extension(ProtocolType):
    def start(self) -> None: ...
    def stop(self) -> None: ...
    def request(self, flow: Flow) -> None: ...
    def response(self, flow: Flow) -> None: ...

def notify(level: int, msg: str) -> None: ...

# Roxy discovers this global list at load
Extensions: List[Extension]
