[package]
name = "roxy"
version = "0.1.0"
description = "CLI proxy tool written in rust aka roxy (rust proxy)."
license = "MIT"
edition = "2024"

[dependencies]
itertools = { version = "0.14", default-features = false, features = [
  "use_alloc",
] }
chrono = "0.4.41"
clap = { version = "4.5.40", features = ["derive"] }
color-eyre = "0.6.3"
crossterm = { version = "0.29.0", features = ["event-stream"] }
directories = "6.0.0"
futures = "0.3.31"
httparse = "1.10.1"
lazy_static = "1.5.0"
ratatui = "0.30.0-alpha.4"
rcgen = { version = "0.13.2", features = [
  "crypto",
  "ring",
  "pem",
  "x509-parser",
] }
rs-snowflake = "0.6.0"
rustls = { version = "0.23", features = ["tls12"] }
tokio = { version = "1.40.0", features = ["full"] }
tokio-rustls = "0.26.2"
tracing = "0.1.41"
tracing-error = "0.2.1"
tracing-subscriber = { version = "0.3.19", features = ["env-filter"] }
unicode-segmentation = "1"
unicode-truncate = { version = "2", default-features = false }
webpki-roots = "1.0.1"
# See <https://github.com/ratatui/ratatui/issues/1271> for information about why we pin unicode-width
unicode-width = "=0.2.0"
anyhow = "1.0.85"
pkcs12 = "0.1.0"
once_cell = "1.19"
mlua = { version = "0.10", features = ["lua54", "vendored", "send"] }
notify = "8.0.0"
dirs = "6.0.0"
hyper = { version = "1.6.0", features = ["full"] }
http-body-util = "0.1"
hyper-util = { version = "0.1", features = ["full"] }
bytes = "1.10.1"
http = "1"
http-body = "1"
x509-parser = "0.17"

[dev-dependencies]
tempfile = "3.11.0"
warp = { version = "0.3.4", features = ["tls", "tokio-rustls"] }
reqwest = { version = "0.12.20" }
