[package]
name = "roxy-shared"
version = "0.1.0"
edition = "2024"

[dependencies]
rcgen = { version = "0.14.1", features = [
  "crypto",
  "aws_lc_rs",
  "pem",
  "x509-parser",
] }
rustls = { version = "0.23", features = ["tls12"] }
tracing = "0.1.37"
tracing-subscriber = "0.3"
anyhow = "1.0.85"
dirs = "6.0.0"
time = "0.3.41"
p12-keystore = "0.2.0"
rand = "0.9.1"
once_cell = "1.19"
