[package]
name = "roxy-shared"
version = "0.1.0"
edition = "2024"

[dependencies]
rcgen = { version = "0.13.2", features = [
  "crypto",
  "ring",
  "pem",
  "x509-parser",
] }
tracing = "0.1.37"
tracing-subscriber = "0.3"
anyhow = "1.0.85"
dirs = "6.0.0"
