[package]
name = "roxy-shared"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = "0.4.41"
dirs = "6.0.0"
once_cell = "1.19"
p12-keystore = "0.2.0"
rcgen = { version = "0.14.1", features = [
  "crypto",
  "aws_lc_rs",
  "pem",
  "x509-parser",
] }
rustls = { version = "0.23", features = ["tls12", "aws-lc-rs"] }
tracing = "0.1.37"
tracing-subscriber = "0.3"
time = "0.3.41"
rand = "0.9.1"
rustls-native-certs = "0.8"
http = "1.3.1"
tokio = { version = "1.46.1", features = ["full"] }

pin-project-lite = "0.2.16"
hyper = { version = "1.6.0", features = ["full"] }
bytes = "1.10.1"
futures = "0.3.31"
hyper-util = { version = "0.1", features = ["full"] }
http-body-util = "0.1"
tokio-rustls = "0.26.2"
futures-util = "0.3"

webpki-roots = "1.0.2"
tokio-native-tls = { version = "0.3.1" }
native-tls = { version = "0.2", features = ["alpn"] }

# Experitmental WT repo
h3 = { git = "https://github.com/fergdev/h3-wt-client", branch = "wt-client" }
h3-quinn = { git = "https://github.com/fergdev/h3-wt-client", branch = "wt-client" }
h3-datagram = { git = "https://github.com/fergdev/h3-wt-client", branch = "wt-client" }
h3-webtransport = { git = "https://github.com/fergdev/h3-wt-client", branch = "wt-client" }

# h3 = { path = "../../h3-wt-client/h3/" }
# h3-quinn = { path = "../../h3-wt-client/h3-quinn/" }
# h3-datagram = { path = "../../h3-wt-client/h3-datagram/" }
# h3-webtransport = { path = "../../h3-wt-client/h3-webtransport/" }

# h3 = "0.0.8"
# h3-quinn = "0.0.10"
# h3-datagram = "0.0.2"
# h3-webtransport = "0.1.2"

# Compression
flate2 = "1.0"
brotli = "8.0.1"
zstd = "0.13"

quinn = { version = "0.11", default-features = false, features = [
  "runtime-tokio",
  "rustls",
  "ring",
] }

# lru_time_cache = "0.11.11" # TODO: look into this
webtransport-quinn = "0.10.0"

strum = "0.27"
strum_macros = "0.27"
